version: '2'
services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      args:
        - APP_HOME=${PWD}
    command: bin/middleman -p 3000
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - .:${PWD}:cached
      - bundle:/vendor/bundle
      - build:/${PWD}/build
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
volumes:
  bundle:
  build:
